# Uncomment the next line to define a global platform for your project

target 'InstaPass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstaPass

  target 'InstaPassTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Alamofire-SwiftyJSON'
# pod "QRCode"
  pod 'EFQRCode', '~> 5.1.6'
  pod 'IQKeyboardManager'
  pod 'SPAlert'
  pod 'Pageboy', '~> 3.6'
  pod 'ImagePicker'
  pod 'QRCodeReader.swift'
end

target 'InstaPass Watch Extension' do
  use_frameworks!
  pod 'EFQRCode/watchOS', '~> 5.1.6'
  pod 'Alamofire'
  pod 'SwiftyJSON'
end