# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'InstaPass' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstaPass

  target 'InstaPassTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Alamofire-SwiftyJSON'
# pod "QRCode"
  pod 'EFQRCode', '~> 5.1.6'
  pod 'EFQRCode/watchOS', '~> 5.1.6'
  pod 'IQKeyboardManager'
  pod 'SPAlert'
end
